/** Linha neutra: fonte decide como projetar, View decide somente apresentação. */
export interface AcademicViewRow { readonly id: string; readonly title: string; readonly fields: Readonly<Record<string, string | number | boolean | undefined>>; }
export interface ProjectViewSource { readonly id: string; readonly title: string; readonly updatedAt: string; readonly archivedAt?: string; readonly milestones: readonly { readonly id: string; readonly title: string; readonly dueDate?: string; readonly completedAt?: string }[]; }
export interface DatasetViewSource { readonly id: string; readonly path: string; readonly metadata: { readonly title: string; readonly creator?: string; readonly collectedAt?: string; readonly version?: string }; readonly format: string; }
export interface ReviewStudyViewSource { readonly id: string; readonly title: string; readonly stage: string; readonly decision?: string; readonly exclusionReason?: string; }
export interface AnnotationViewSource { readonly id: string; readonly referenceId: string; readonly page: number; readonly quote: string; readonly comment?: string; readonly createdAt: string; }
export const projectViewRows = (items: readonly ProjectViewSource[]): readonly AcademicViewRow[] => items.map((item) => ({ id: item.id, title: item.title, fields: { updatedAt: item.updatedAt, status: item.archivedAt === undefined ? 'active' : 'archived', milestones: item.milestones.length, nextDeadline: item.milestones.find((milestone) => milestone.completedAt === undefined)?.dueDate } }));
export const datasetViewRows = (items: readonly DatasetViewSource[]): readonly AcademicViewRow[] => items.map((item) => ({ id: item.id, title: item.metadata.title, fields: { path: item.path, format: item.format, creator: item.metadata.creator, collectedAt: item.metadata.collectedAt, version: item.metadata.version } }));
export const reviewStudyViewRows = (items: readonly ReviewStudyViewSource[]): readonly AcademicViewRow[] => items.map((item) => ({ id: item.id, title: item.title, fields: { stage: item.stage, decision: item.decision, exclusionReason: item.exclusionReason } }));
export const annotationViewRows = (items: readonly AnnotationViewSource[]): readonly AcademicViewRow[] => items.map((item) => ({ id: item.id, title: item.quote.slice(0, 120), fields: { referenceId: item.referenceId, page: item.page, comment: item.comment, createdAt: item.createdAt } }));
