import type { EvidenceLink, ExclusionReason, ExtractionField, ExtractionValue, PrismaFlow, QualityAssessment, QualityItem, ReviewProtocol, ReviewStudy, ReviewerDecision, ScreeningDecision, ScreeningStage, SearchStrategyRecord } from './model.js';

export const frameworkTemplate = (framework: ReviewProtocol['framework']): Readonly<Record<string, string>> => ({
  freeform: {}, pico: { population: '', intervention: '', comparison: '', outcome: '' }, picos: { population: '', intervention: '', comparison: '', outcome: '', studyDesign: '' }, spider: { sample: '', phenomenon: '', design: '', evaluation: '', researchType: '' },
}[framework]);

export function createProtocol(input: Omit<ReviewProtocol, 'frameworkFields'> & { readonly frameworkFields?: Readonly<Record<string, string>> }): ReviewProtocol {
  return { ...input, title: input.title.trim(), question: input.question.trim(), databases: [...new Set(input.databases.map((item) => item.trim()).filter(Boolean))], frameworkFields: { ...frameworkTemplate(input.framework), ...input.frameworkFields } };
}
export function addSearchRecord(records: readonly SearchStrategyRecord[], record: SearchStrategyRecord): readonly SearchStrategyRecord[] { return [...records, { ...record, database: record.database.trim(), query: record.query.trim(), resultCount: Math.max(0, record.resultCount) }]; }
export function recordDecision(study: ReviewStudy, decision: ReviewerDecision): ReviewStudy { return { ...study, decisions: [...study.decisions.filter((item) => item.reviewerId !== decision.reviewerId), decision] }; }
export function resolveScreening(study: ReviewStudy, stage: ScreeningStage, decisions: readonly ReviewerDecision[], reasonId?: string): ReviewStudy { const decision = decisions.at(-1)?.decision; return { ...study, stage: decision === 'exclude' ? 'excluded' : decision === 'include' ? stage : study.stage, decisions, ...(decision === 'exclude' && reasonId !== undefined ? { exclusionReasonId: reasonId } : {}) }; }
export function screeningQueue(studies: readonly ReviewStudy[], stage: ScreeningStage): readonly ReviewStudy[] { return studies.filter((study) => study.stage === stage && study.decisions.every((decision) => decision.decision !== 'exclude')); }
export function screeningAgreement(studies: readonly ReviewStudy[]): { readonly agreed: number; readonly conflicts: readonly ReviewStudy[] } { const eligible = studies.filter((study) => study.decisions.length >= 2); const conflicts = eligible.filter((study) => new Set(study.decisions.map((item) => item.decision)).size > 1); return { agreed: eligible.length - conflicts.length, conflicts }; }
export function validateExtraction(schema: readonly ExtractionField[], values: readonly ExtractionValue[]): readonly string[] { const byId = new Map(values.map((value) => [value.fieldId, value.value])); return schema.flatMap((field) => { const value = byId.get(field.id); if (field.required && (value === undefined || value === '')) return [`${field.label} é obrigatório.`]; if (value !== undefined && field.type === 'number' && typeof value !== 'number') return [`${field.label} deve ser numérico.`]; if (field.type === 'select' && typeof value === 'string' && field.options !== undefined && !field.options.includes(value)) return [`${field.label} contém uma opção inválida.`]; return []; }); }
export function prismaFlow(studies: readonly ReviewStudy[]): PrismaFlow { const count = (stage: ScreeningStage): number => studies.filter((study) => study.stage === stage).length; return { identified: count('identified'), deduplicated: count('deduplicated'), titleScreened: count('title-screened'), abstractScreened: count('abstract-screened'), fullText: count('full-text'), included: count('included'), excluded: count('excluded') }; }
export function evidenceTable(studies: readonly ReviewStudy[], fields: readonly ExtractionField[], values: Readonly<Record<string, readonly ExtractionValue[]>>): readonly { readonly studyId: string; readonly title: string; readonly values: Readonly<Record<string, string | number | boolean | undefined>> }[] { return studies.filter((study) => study.stage === 'included').map((study) => ({ studyId: study.id, title: study.title, values: Object.fromEntries(fields.map((field) => [field.id, values[study.id]?.find((value) => value.fieldId === field.id)?.value])) })); }
export function qualityScore(items: readonly QualityItem[], assessment: QualityAssessment): { readonly answered: number; readonly favorable: number; readonly total: number } { const valid = assessment.answers.filter((answer) => items.some((item) => item.id === answer.itemId) && answer.value !== 'na'); return { answered: valid.length, favorable: valid.filter((answer) => answer.value === 'yes').length, total: items.length }; }
export function evidenceToWriting(link: EvidenceLink): EvidenceLink { return { ...link }; }
export function exclusionLabel(reasons: readonly ExclusionReason[], id: string | undefined): string | undefined { return reasons.find((reason) => reason.id === id)?.label; }
export type { ScreeningDecision };
