import { type JSX } from 'react';
import type { WorkspaceEvidenceSynthesisDto } from '@abnt/protocol';
import { evidenceMap, evidenceOverview, evidenceTable, exportEvidenceSynthesis, narrativeSynthesis, reproducibilityPackage } from '@abnt/evidence-synthesis';

const download = (name: string, value: string, type: string): void => { const url = URL.createObjectURL(new Blob([value], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };

export function EvidenceReporting({ synthesis, onMessage }: { readonly synthesis: WorkspaceEvidenceSynthesisDto; readonly onMessage: (message: string) => void; }): JSX.Element {
  const overview = evidenceOverview(synthesis as never); const table = evidenceTable(synthesis as never); const map = evidenceMap(synthesis as never);
  const exportFile = (format: 'csv' | 'tsv' | 'json'): void => { download('folio-evidence-synthesis.' + format, exportEvidenceSynthesis(synthesis as never, format), format === 'json' ? 'application/json' : 'text/plain'); onMessage('Exportação local preparada para análise externa.'); };
  const exportReproducibility = (): void => { download('folio-reproducibility-package.json', JSON.stringify(reproducibilityPackage(synthesis as never), null, 2), 'application/json'); onMessage('Pacote reprodutível preparado sem bytes de PDF.'); };
  void exportReproducibility;
  return <div className="grid gap-5 pr-8"><div><h3 className="text-xl font-bold text-slate-900">Síntese e reporting</h3><p className="mt-1 text-sm text-slate-500">Visões derivadas do vault. Feeds e monitoramento continuam entrando somente pela inbox revisável.</p></div>
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(overview).map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs text-slate-500">{label}</p><b className="text-xl">{value}</b></div>)}</section>
    <section className="grid gap-3 rounded-xl border border-slate-200 p-4"><h4 className="font-semibold">Síntese narrativa</h4><p className="text-sm leading-6 text-slate-700">{narrativeSynthesis(synthesis as never)}</p></section>
    <section className="grid gap-3 rounded-xl border border-slate-200 p-4"><h4 className="font-semibold">Mapa de evidência</h4>{map.length === 0 ? <p className="text-sm text-slate-500">Registre extrações para formar o mapa.</p> : map.map((entry) => <div key={entry.fieldId} className="flex items-center gap-3 text-sm"><span className="w-40 truncate">{entry.fieldId}</span><div className="h-3 flex-1 rounded bg-slate-100"><div className="h-3 rounded bg-indigo-600" style={{ width: String(Math.min(100, entry.count * 16)) + '%' }} /></div><b>{entry.count}</b></div>)}</section>
    <section className="grid gap-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2"><h4 className="mr-auto font-semibold">Tabela de evidência</h4><button type="button" className="rounded border px-2 py-1 text-sm" onClick={() => exportFile('csv')}>CSV</button><button type="button" className="rounded border px-2 py-1 text-sm" onClick={() => exportFile('tsv')}>TSV</button><button type="button" className="rounded border px-2 py-1 text-sm" onClick={() => exportFile('json')}>JSON</button></div>{table.length === 0 ? <p className="text-sm text-slate-500">Nenhum item de evidência admitido.</p> : <div className="overflow-auto"><table className="min-w-full text-left text-xs"><thead><tr>{Object.keys(table[0] ?? {}).map((column) => <th key={column} className="border-b p-2">{column}</th>)}</tr></thead><tbody>{table.map((row, index) => <tr key={index}>{Object.keys(table[0] ?? {}).map((column) => <td key={column} className="border-b p-2">{row[column]}</td>)}</tr>)}</tbody></table></div>}</section>
  </div>;
}
