import { useState, type JSX } from 'react';
import type { WorkspaceEvidenceSynthesisDto } from '@abnt/protocol';
import { admitInboxItem, assessmentState, createAssessmentStage, createCriterion, reconcileEvidenceItem, recordEvidenceDecision } from '@abnt/evidence-synthesis';

type Decision = 'include' | 'exclude' | 'maybe';

export function EvidenceAssessment({ synthesis, onSave, onMessage }: { readonly synthesis: WorkspaceEvidenceSynthesisDto; readonly onSave: (value: WorkspaceEvidenceSynthesisDto) => Promise<void>; readonly onMessage: (message: string) => void; }): JSX.Element {
  const [stageLabel, setStageLabel] = useState(''); const [reviewers, setReviewers] = useState('1'); const [reasonRequired, setReasonRequired] = useState(false); const [criterionLabel, setCriterionLabel] = useState(''); const [activeStageId, setActiveStageId] = useState(synthesis.stages[0]?.id ?? ''); const [reviewerId, setReviewerId] = useState('local'); const [reason, setReason] = useState('');
  const input = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';
  const update = (operation: (current: WorkspaceEvidenceSynthesisDto) => WorkspaceEvidenceSynthesisDto): void => { try { void onSave(operation(synthesis)); } catch (error) { onMessage(error instanceof Error ? error.message : 'Não foi possível atualizar a avaliação.'); } };
  const selectedStageId = activeStageId || synthesis.stages[0]?.id;
  const decide = (evidenceItemId: string, decision: Decision, reconciled: boolean): void => update((current) => {
    if (selectedStageId === undefined) throw new Error('Crie ou selecione um estágio.');
    const at = new Date().toISOString(); const reviewer = reviewerId.trim() || 'local';
    return (reconciled ? reconcileEvidenceItem(current as never, { evidenceItemId, stageId: selectedStageId, decision, reconciledBy: reviewer, reconciledAt: at, ...(reason.trim() === '' ? {} : { note: reason.trim() }) }) : recordEvidenceDecision(current as never, { evidenceItemId, stageId: selectedStageId, reviewerId: reviewer, decision, at, ...(reason.trim() === '' ? {} : { reasonId: reason.trim() }) })) as unknown as WorkspaceEvidenceSynthesisDto;
  });
  return <div className="grid gap-5 pr-8"><div><h3 className="text-xl font-bold text-slate-900">Avaliação configurável</h3><p className="mt-1 text-sm text-slate-500">Estágios e decisões pertencem à síntese. Biblioteca e relações acadêmicas permanecem independentes.</p></div>
    <section className="grid gap-3 rounded-xl border border-slate-200 p-4"><h4 className="font-semibold">Estágios e critérios</h4><div className="grid gap-2 sm:grid-cols-3"><input value={stageLabel} onChange={(event) => setStageLabel(event.target.value)} placeholder="Nome do estágio" className={input} /><input value={reviewers} onChange={(event) => setReviewers(event.target.value)} inputMode="numeric" placeholder="Revisores" className={input} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={reasonRequired} onChange={(event) => setReasonRequired(event.target.checked)} />Motivo obrigatório ao excluir</label></div>
      <button type="button" className="justify-self-start rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white" onClick={() => update((current) => { const stage = createAssessmentStage({ label: stageLabel, decisions: ['include', 'exclude', 'maybe'], reviewersRequired: Number(reviewers) || 1, blind: false, exclusionReasonRequired: reasonRequired }); setStageLabel(''); setActiveStageId(stage.id); return { ...current, stages: [...current.stages, stage] }; })}>Adicionar estágio</button>
      {synthesis.stages.map((stage) => <button key={stage.id} type="button" className={'rounded-lg border p-2 text-left text-sm ' + (selectedStageId === stage.id ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200')} onClick={() => setActiveStageId(stage.id)}>{stage.label} · {stage.reviewersRequired} revisor(es) · {stage.exclusionReasonRequired ? 'motivo obrigatório' : 'motivo opcional'}</button>)}
      <div className="flex gap-2"><input value={criterionLabel} onChange={(event) => setCriterionLabel(event.target.value)} placeholder="Critério de inclusão" className={input} /><button type="button" className="rounded-lg border border-indigo-300 px-3 text-sm font-medium text-indigo-700" onClick={() => update((current) => { if (selectedStageId === undefined) throw new Error('Crie um estágio antes de adicionar critérios.'); const criterion = createCriterion({ label: criterionLabel, stageId: selectedStageId, polarity: 'include', required: false }, current.stages as never); setCriterionLabel(''); return { ...current, criteria: [...current.criteria, criterion] }; })}>Adicionar critério</button></div>
      {synthesis.criteria.map((criterion) => <p key={criterion.id} className="text-xs text-slate-600">{criterion.label} · {synthesis.stages.find((stage) => stage.id === criterion.stageId)?.label}</p>)}</section>
    <section className="grid gap-3 rounded-xl border border-slate-200 p-4"><h4 className="font-semibold">Inbox pronta para avaliação</h4>{synthesis.inbox.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><span className="min-w-0 flex-1 truncate text-sm">{item.title}</span><button type="button" className="rounded border px-2 py-1 text-sm" onClick={() => update((current) => admitInboxItem(current as never, item.id) as unknown as WorkspaceEvidenceSynthesisDto)}>Adicionar à avaliação</button></div>)}{synthesis.inbox.length === 0 && <p className="text-sm text-slate-500">Nenhum candidato pendente na inbox.</p>}</section>
    <section className="grid gap-3 rounded-xl border border-indigo-200 bg-indigo-50/30 p-4"><h4 className="font-semibold">Decisão e reconciliação</h4><div className="grid grid-cols-2 gap-2"><input value={reviewerId} onChange={(event) => setReviewerId(event.target.value)} placeholder="Identificador do revisor" className={input} /><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Motivo ou nota de reconciliação" className={input} /></div>
      {synthesis.evidenceItems.map((item) => { const state = selectedStageId === undefined ? 'pending' : assessmentState(synthesis as never, item.id, selectedStageId); return <div key={item.id} className="grid gap-2 rounded-lg border border-indigo-100 bg-white p-3"><div className="flex gap-2"><b className="mr-auto text-sm">{item.label}</b><span className="text-xs text-slate-500">{state}</span></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => decide(item.id, 'include', false)}>Incluir</button><button type="button" onClick={() => decide(item.id, 'exclude', false)}>Excluir</button><button type="button" onClick={() => decide(item.id, 'maybe', false)}>Rever</button>{state === 'conflict' && <><button type="button" className="rounded border border-indigo-300 px-2 py-1 text-sm text-indigo-700" onClick={() => decide(item.id, 'include', true)}>Reconciliar: incluir</button><button type="button" className="rounded border border-indigo-300 px-2 py-1 text-sm text-indigo-700" onClick={() => decide(item.id, 'exclude', true)}>Reconciliar: excluir</button></>}</div></div>; })}
    </section></div>;
}
