import { useEffect, useState, type JSX } from 'react';
import type { WorkspaceEvidenceSynthesisDto } from '@abnt/protocol';
import { claimManuscriptDraft, claimProvenance, claimReadiness, createEvidenceClaim, linkClaimEvidence, linkWorkReference, livingClaimStatus, recordExtraction } from '@abnt/evidence-synthesis';

export interface EvidenceAnnotationDraft {
  readonly id: string;
  readonly fileId?: string;
  readonly page: number;
  readonly quote: string;
}

export function EvidenceFullText({ synthesis, annotationDraft, onSave, onMessage, onOpenPdf }: { readonly synthesis: WorkspaceEvidenceSynthesisDto; readonly annotationDraft?: EvidenceAnnotationDraft; readonly onSave: (value: WorkspaceEvidenceSynthesisDto) => Promise<void>; readonly onMessage: (message: string) => void; readonly onOpenPdf: (fileId: string, page: number) => void; }): JSX.Element {
  const [workId, setWorkId] = useState(synthesis.works[0]?.id ?? ''); const [referenceId, setReferenceId] = useState(''); const [candidates, setCandidates] = useState<readonly { provider: string; url: string; license: string; confidence: number }[]>([]);
  const [evidenceItemId, setEvidenceItemId] = useState(synthesis.evidenceItems[0]?.id ?? ''); const [fieldId, setFieldId] = useState('summary'); const [value, setValue] = useState(''); const [page, setPage] = useState(''); const [annotationId, setAnnotationId] = useState(''); const [reviewer, setReviewer] = useState('local'); const [selectedExtractionId, setSelectedExtractionId] = useState<string>();
  const [claimLabel, setClaimLabel] = useState(''); const [claimWorkId, setClaimWorkId] = useState(synthesis.works[0]?.id ?? ''); const [claimId, setClaimId] = useState(''); const [claimTargetId, setClaimTargetId] = useState(''); const [claimRelation, setClaimRelation] = useState<'supports' | 'contradicts'>('supports');
  const [draftClaimId, setDraftClaimId] = useState(''); const [draft, setDraft] = useState(''); const provenance = draftClaimId === '' ? [] : claimProvenance(synthesis as never, draftClaimId); const readiness = draftClaimId === '' ? undefined : claimReadiness(synthesis as never, draftClaimId);
  const living = draftClaimId === '' ? undefined : livingClaimStatus(synthesis as never, draftClaimId); void living;
  const input = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';
  const currentWork = synthesis.works.find((item) => item.id === workId);
  const selectedExtraction = synthesis.extractions.find((item) => item.id === selectedExtractionId);
  const selectedEvidenceItem = selectedExtraction === undefined ? undefined : synthesis.evidenceItems.find((item) => item.id === selectedExtraction.evidenceItemId);
  const selectedWork = selectedEvidenceItem === undefined ? undefined : synthesis.works.find((item) => item.id === selectedEvidenceItem.workId);
  const selectedArtifact = selectedExtraction?.artifactId === undefined ? undefined : synthesis.artifacts.find((item) => item.id === selectedExtraction.artifactId);
  const save = (next: WorkspaceEvidenceSynthesisDto): void => { void onSave(next); };
  useEffect(() => {
    if (annotationDraft === undefined) return;
    setValue(annotationDraft.quote);
    setPage(String(annotationDraft.page));
    setAnnotationId(annotationDraft.id);
  }, [annotationDraft]);
  const find = async (): Promise<void> => {
    const id = referenceId.trim() || currentWork?.referenceId;
    if (id === undefined || id === '') { onMessage('Vincule uma referência da biblioteca à obra antes de buscar texto completo.'); return; }
    const linked = currentWork?.referenceId === id ? synthesis : linkWorkReference(synthesis as never, workId, id) as unknown as WorkspaceEvidenceSynthesisDto;
    save(linked);
    const result = await window.academic.library.discoverFullText({ referenceId: id });
    if (result.ok) setCandidates(result.value.candidates); else onMessage(result.error.message);
  };
  const download = async (url: string): Promise<void> => {
    const id = referenceId.trim() || currentWork?.referenceId;
    if (id === undefined || id === '' || currentWork === undefined) return;
    const result = await window.academic.library.downloadFullText({ referenceId: id, url, displayTitle: currentWork.title });
    if (!result.ok) { onMessage(result.error.message); return; }
    const artifactId = 'artifact:' + result.value.id;
    save({ ...synthesis, works: synthesis.works.map((work) => work.id === workId ? { ...work, referenceId: id, fullText: 'available', artifactIds: [...work.artifactIds, artifactId] } : work), artifacts: [...synthesis.artifacts, { id: artifactId, workId, attachmentId: result.value.id, kind: 'pdf' }] });
    setCandidates([]); onMessage('Texto completo anexado após confirmação.');
  };
  const extract = (): void => {
    try {
      const artifactId = currentWork?.artifactIds[0];
      const next = recordExtraction(synthesis as never, { id: crypto.randomUUID(), evidenceItemId, fieldId, value, ...(artifactId === undefined ? {} : { artifactId }), ...(page.trim() === '' ? {} : { page: Number(page) }), ...(annotationId.trim() === '' ? {} : { annotationId: annotationId.trim() }), reviewerId: reviewer.trim() || 'local', verifiedAt: new Date().toISOString() }) as unknown as WorkspaceEvidenceSynthesisDto;
      save(next); setValue('');
    } catch (error) { onMessage(error instanceof Error ? error.message : 'Não foi possível registrar a extração.'); }
  };
  const openAnnotation = async (id: string): Promise<void> => {
    const result = await window.academic.library.pdfAnnotations({});
    if (!result.ok) { onMessage(result.error.message); return; }
    const annotation = result.value.find((item) => item.id === id);
    if (annotation?.fileId === undefined) { onMessage('A anotação não aponta para um arquivo PDF disponível neste vault.'); return; }
    onOpenPdf(annotation.fileId, annotation.page);
  };
  const createClaim = (): void => { try { const next = createEvidenceClaim(synthesis as never, { id: crypto.randomUUID(), workId: claimWorkId, label: claimLabel }) as unknown as WorkspaceEvidenceSynthesisDto; save(next); setClaimId(next.evidenceItems.at(-1)?.id ?? ''); setClaimLabel(''); onMessage('Claim criada para revisão.'); } catch (error) { onMessage(error instanceof Error ? error.message : 'Não foi possível criar a claim.'); } };
  const relateClaim = (): void => { try { save(linkClaimEvidence(synthesis as never, { claimId, evidenceItemId: claimTargetId, relation: claimRelation, reviewerId: reviewer.trim() || 'local', createdAt: new Date().toISOString() }) as unknown as WorkspaceEvidenceSynthesisDto); onMessage(claimRelation === 'supports' ? 'Evidência ligada como suporte.' : 'Evidência ligada como contradição.'); } catch (error) { onMessage(error instanceof Error ? error.message : 'Não foi possível ligar a evidência.'); } };
  const previewDraft = (): void => { try { if (readiness?.ready !== true) { onMessage('A claim precisa de evidência relacionada com extração auditável antes da prévia.'); return; } setDraft(claimManuscriptDraft(synthesis as never, draftClaimId)); } catch (error) { onMessage(error instanceof Error ? error.message : 'Não foi possível gerar o rascunho.'); } };
  return <div className="grid gap-5 pr-8"><div><h3 className="text-xl font-bold text-slate-900">Texto completo e extração</h3><p className="mt-1 text-sm text-slate-500">Descoberta não baixa nada. O PDF só vira anexo após confirmação; extrações conservam sua origem.</p></div>
    <section className="grid gap-3 rounded-xl border border-sky-200 bg-sky-50/30 p-4"><h4 className="font-semibold">Descoberta e PDF</h4><select value={workId} onChange={(event) => { setWorkId(event.target.value); setReferenceId(synthesis.works.find((work) => work.id === event.target.value)?.referenceId ?? ''); }} className={input}><option value="">Escolha uma obra</option>{synthesis.works.map((work) => <option key={work.id} value={work.id}>{work.title}</option>)}</select><input value={referenceId} onChange={(event) => setReferenceId(event.target.value)} placeholder="ID da referência na Biblioteca" className={input} /><button type="button" className="justify-self-start rounded-lg bg-sky-700 px-3 py-2 text-sm font-medium text-white" onClick={() => void find()}>Buscar candidatos</button>{candidates.map((candidate) => <div key={candidate.url} className="flex flex-wrap items-center gap-2 rounded-lg bg-white p-3 text-sm"><b>{candidate.provider}</b><span>{candidate.license}</span><span className="min-w-0 flex-1 truncate">{candidate.url}</span><button type="button" className="rounded border border-sky-300 px-2 py-1 text-sky-800" onClick={() => void download(candidate.url)}>Baixar e anexar</button></div>)}</section>
    <section className="grid gap-3 rounded-xl border border-slate-200 p-4"><h4 className="font-semibold">Extração auditável</h4>{annotationDraft !== undefined && <div className="rounded-lg border border-indigo-200 bg-indigo-50 p-3 text-sm"><b>Anotação recebida · p. {annotationDraft.page}</b><p className="mt-1 line-clamp-3 text-slate-700">{annotationDraft.quote}</p><p className="mt-1 text-xs text-slate-500">A extração guarda apenas o ID e a página da anotação; o texto canônico continua no sidecar do PDF.</p></div>}<select value={evidenceItemId} onChange={(event) => setEvidenceItemId(event.target.value)} className={input}><option value="">Escolha um item de evidência</option>{synthesis.evidenceItems.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><div className="grid gap-2 sm:grid-cols-2"><input value={fieldId} onChange={(event) => setFieldId(event.target.value)} placeholder="Campo de extração" className={input} /><input value={reviewer} onChange={(event) => setReviewer(event.target.value)} placeholder="Revisor" className={input} /></div><textarea value={value} onChange={(event) => setValue(event.target.value)} placeholder="Texto, rich-text, identificador ou valor estruturado revisado" className={input} /><div className="grid gap-2 sm:grid-cols-2"><input value={page} onChange={(event) => setPage(event.target.value)} inputMode="numeric" placeholder="Página do artefato" className={input} /><input value={annotationId} onChange={(event) => setAnnotationId(event.target.value)} placeholder="ID de anotação (opcional)" className={input} /></div><button type="button" className="justify-self-start rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white" onClick={extract}>Registrar extração</button>{synthesis.extractions.map((item) => <button type="button" key={item.id} className="flex w-full flex-wrap items-center gap-2 rounded bg-slate-50 p-2 text-left text-xs hover:bg-indigo-50" onClick={() => setSelectedExtractionId(item.id) }><span>{item.fieldId}: {typeof item.value === 'string' ? item.value : JSON.stringify(item.value)} · revisado por {item.reviewerId}{item.page === undefined ? '' : ' · p. ' + item.page}</span>{item.annotationId !== undefined && <button type="button" className="font-medium text-indigo-700" onClick={() => void openAnnotation(item.annotationId!)}>Abrir anotação no PDF</button>}</button>)}</section>
    <section className="grid gap-3 rounded-xl border border-amber-200 bg-amber-50/30 p-4"><h4 className="font-semibold">Claims e relações</h4><p className="text-sm text-slate-600">Registre um enunciado e marque quais evidências o sustentam ou contradizem.</p><div className="grid gap-2 sm:grid-cols-2"><input value={claimLabel} onChange={(event) => setClaimLabel(event.target.value)} placeholder="Enunciado da claim" className={input} /><select value={claimWorkId} onChange={(event) => setClaimWorkId(event.target.value)} className={input}>{synthesis.works.map((work) => <option key={work.id} value={work.id}>{work.title}</option>)}</select></div><button type="button" className="justify-self-start rounded-lg bg-amber-700 px-3 py-2 text-sm font-medium text-white" onClick={createClaim}>Criar claim</button><div className="grid gap-2 sm:grid-cols-3"><select value={claimId} onChange={(event) => setClaimId(event.target.value)} className={input}><option value="">Escolha uma claim</option>{synthesis.evidenceItems.filter((item) => item.kind === 'claim').map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select value={claimTargetId} onChange={(event) => setClaimTargetId(event.target.value)} className={input}><option value="">Evidência relacionada</option>{synthesis.evidenceItems.filter((item) => item.kind !== 'claim').map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select value={claimRelation} onChange={(event) => setClaimRelation(event.target.value as 'supports' | 'contradicts')} className={input}><option value="supports">Sustenta</option><option value="contradicts">Contradiz</option></select></div><button type="button" className="justify-self-start rounded-lg border border-amber-700 px-3 py-2 text-sm font-medium text-amber-800" onClick={relateClaim}>Ligar evidência</button>{(synthesis.claimRelations ?? []).map((relation) => <div key={relation.id} className="text-xs text-slate-600">{synthesis.evidenceItems.find((item) => item.id === relation.claimId)?.label} · <b>{relation.relation === 'supports' ? 'sustenta' : 'contradiz'}</b> · {synthesis.evidenceItems.find((item) => item.id === relation.evidenceItemId)?.label}</div>)}</section>
    <section className="grid gap-3 rounded-xl border border-emerald-200 bg-emerald-50/30 p-4"><h4 className="font-semibold">Claim para o manuscrito</h4><p className="text-sm text-slate-600">Gere uma prévia Markdown com a proveniência. A inserção no documento só deve ocorrer após revisão explícita.</p><select value={draftClaimId} onChange={(event) => setDraftClaimId(event.target.value)} className={input}><option value="">Escolha uma claim</option>{synthesis.evidenceItems.filter((item) => item.kind === 'claim').map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select>{readiness !== undefined && <p className={`text-xs ${readiness.ready ? 'text-emerald-700' : 'text-amber-700'}`}>{readiness.ready ? 'Pronta para revisão editorial.' : `${readiness.relationCount} relação(ões), ${readiness.relationsWithoutExtraction} sem extração auditável.`}</p>}<button type="button" disabled={readiness?.ready !== true} className="justify-self-start rounded-lg bg-emerald-700 px-3 py-2 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-50" onClick={previewDraft}>Gerar prévia</button>{provenance.length > 0 && <div className="grid gap-2 text-xs text-slate-600" aria-label="Proveniência da claim">{provenance.map((entry) => <div key={entry.evidenceItemId} className="rounded bg-white p-2"><b>{entry.relation === 'supports' ? 'Suporte' : 'Contradição'}</b> · {entry.workTitle} · {entry.extractionIds.length} extração(ões) · {entry.pages.length > 0 ? `p. ${entry.pages.join(', ')}` : 'sem página'}{entry.annotationIds.length > 0 ? ` · ${entry.annotationIds.length} annotation(s)` : ''}</div>)}</div>}{draft !== '' && <textarea readOnly value={draft} className={`${input} min-h-32 font-mono`} aria-label="Prévia do manuscrito" />}</section>
    {selectedExtraction !== undefined && <aside className="rounded-xl border border-indigo-200 bg-indigo-50/50 p-4" aria-label="Inspetor de proveniência"><div className="flex items-center justify-between"><h4 className="font-semibold text-indigo-950">Proveniência da extração</h4><button type="button" className="text-xs font-medium text-indigo-700" onClick={() => setSelectedExtractionId(undefined)}>Fechar</button></div><p className="mt-3 text-sm text-slate-700">{selectedExtraction.fieldId}: {typeof selectedExtraction.value === 'string' ? selectedExtraction.value : JSON.stringify(selectedExtraction.value)}</p><ol className="mt-3 grid gap-2 text-xs text-slate-600"><li><b>Extração</b> · {selectedExtraction.id}</li><li><b>Annotation</b> · {selectedExtraction.annotationId ?? 'não vinculada'}{selectedExtraction.page === undefined ? '' : ` · página ${selectedExtraction.page}`}</li><li><b>Artifact</b> · {selectedArtifact?.id ?? 'não vinculado'}</li><li><b>Obra</b> · {selectedWork?.title ?? 'não encontrada'}</li><li><b>Referência</b> · {selectedWork?.referenceId ?? 'não vinculada'}</li></ol>{selectedExtraction.annotationId !== undefined && <button type="button" className="mt-3 text-xs font-medium text-indigo-700" onClick={() => void openAnnotation(selectedExtraction.annotationId!)}>Abrir annotation no PDF</button>}</aside>}
  </div>;
}
