import { useEffect, useState, type JSX } from 'react';
import type { WorkspacePluginDto } from '@abnt/protocol';

/** F91/F93: surface declarativa; nenhum componente ou código de plugin entra no renderer. */
export function PluginManagerDialog({ onClose }: { readonly onClose: () => void }): JSX.Element {
  const [plugins, setPlugins] = useState<readonly WorkspacePluginDto[]>([]); const [message, setMessage] = useState(''); const [view, setView] = useState<{ readonly title: string; readonly body: string } | undefined>();
  const load = (): void => { void window.academic.workspace.plugins().then((result) => { if (result.ok) setPlugins(result.value); else setMessage(result.error.message); }); };
  useEffect(load, []);
  const toggle = (plugin: WorkspacePluginDto): void => { void window.academic.workspace.setPluginEnabled({ id: plugin.id, enabled: !plugin.enabled }).then((result) => { if (result.ok) setPlugins(result.value); else setMessage(result.error.message); }); };
  const reload = (): void => { void window.academic.workspace.reloadPlugins().then((result) => { if (result.ok) { setPlugins(result.value); setMessage('Plugins recarregados.'); } else setMessage(result.error.message); }); };
  return <div className="fixed inset-0 z-[58] grid place-items-center bg-slate-950/45 p-5"><section role="dialog" aria-modal="true" aria-labelledby="plugins-title" className="flex h-[min(80vh,48rem)] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex border-b border-slate-200 px-6 py-4"><div><h2 id="plugins-title" className="text-lg font-bold text-slate-900">Plugins locais</h2><p className="text-sm text-slate-500">Descobertos em <code>.academic/plugins</code>. Isolamento contém falhas, não é sandbox de segurança.</p></div><button type="button" className="ml-auto text-xl text-slate-500" onClick={onClose}>×</button></header><div className="flex gap-2 border-b border-slate-100 px-6 py-3"><button type="button" onClick={reload} className="rounded bg-indigo-600 px-3 py-1.5 text-sm text-white">Recarregar</button>{message !== '' && <span className="self-center text-sm text-slate-500">{message}</span>}</div><div className="min-h-0 flex-1 overflow-auto p-5"><ul className="grid gap-3">{plugins.length === 0 ? <li className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Nenhum plugin local encontrado.</li> : plugins.map((plugin) => <li key={plugin.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start gap-3"><div><strong className="text-slate-800">{plugin.id}</strong><span className="ml-2 text-xs text-slate-500">{plugin.version ?? 'manifesto inválido'}</span><p className="mt-1 text-xs text-slate-500">{plugin.capabilities.join(', ') || plugin.error || 'sem capabilities'}</p></div><button type="button" disabled={plugin.error !== undefined} onClick={() => toggle(plugin)} className="ml-auto rounded px-3 py-1.5 text-sm font-medium text-indigo-700 hover:bg-indigo-50 disabled:opacity-40">{plugin.enabled ? 'Desabilitar' : 'Habilitar'}</button></div>{plugin.error !== undefined && <p className="mt-2 text-sm text-rose-600">{plugin.error}</p>}{plugin.views.map((item) => <button key={item.id} type="button" onClick={() => setView(item)} className="mt-3 mr-2 rounded bg-slate-100 px-2 py-1 text-xs font-medium text-slate-700">Abrir: {item.title}</button>)}</li>)}</ul>{view !== undefined && <section className="mt-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4"><div className="flex"><strong className="text-sm text-indigo-900">{view.title}</strong><button type="button" className="ml-auto" onClick={() => setView(undefined)}>×</button></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{view.body}</p></section>}</div></section></div>;
}
