export type AcademicFieldKind = 'text' | 'textarea' | 'number' | 'date' | 'select' | 'boolean';
export interface AcademicFormField { readonly id: string; readonly label: string; readonly kind: AcademicFieldKind; readonly required?: boolean; readonly options?: readonly { readonly value: string; readonly label: string }[]; }
export interface AcademicFormSchema { readonly id: string; readonly title: string; readonly fields: readonly AcademicFormField[]; }
export type AcademicFormValues = Readonly<Record<string, string | number | boolean | undefined>>;
export function validateForm(schema: AcademicFormSchema, values: AcademicFormValues): readonly { readonly field: string; readonly message: string }[] { const ids = new Set<string>(); const problems: { field: string; message: string }[] = []; for (const field of schema.fields) { if (field.id.trim() === '' || ids.has(field.id)) problems.push({ field: field.id, message: 'Campo inválido ou duplicado.' }); ids.add(field.id); const value = values[field.id]; if (field.required && (value === undefined || value === '')) problems.push({ field: field.id, message: 'Campo obrigatório.' }); if (value !== undefined && field.kind === 'number' && typeof value !== 'number') problems.push({ field: field.id, message: 'Informe um número.' }); if (value !== undefined && field.kind === 'boolean' && typeof value !== 'boolean') problems.push({ field: field.id, message: 'Informe verdadeiro ou falso.' }); if (field.options !== undefined && value !== undefined && !field.options.some((option) => option.value === value)) problems.push({ field: field.id, message: 'Opção inválida.' }); } return problems; }
export const systematicReviewExtractionForm = (fields: readonly { readonly id: string; readonly label: string; readonly required?: boolean }[]): AcademicFormSchema => ({ id: 'systematic-review-extraction', title: 'Extração de estudo', fields: fields.map((field) => ({ ...field, kind: 'textarea' })) });
export const datasetMetadataForm: AcademicFormSchema = { id: 'dataset-metadata', title: 'Metadata do dataset', fields: [{ id: 'title', label: 'Título', kind: 'text', required: true }, { id: 'description', label: 'Descrição', kind: 'textarea' }, { id: 'license', label: 'Licença', kind: 'text' }, { id: 'collectionDate', label: 'Data de coleta', kind: 'date' }] };
export const referenceReviewForm: AcademicFormSchema = { id: 'reference-review', title: 'Revisar referência', fields: [{ id: 'title', label: 'Título', kind: 'text', required: true }, { id: 'authors', label: 'Autores', kind: 'textarea' }, { id: 'year', label: 'Ano', kind: 'number' }, { id: 'doi', label: 'DOI', kind: 'text' }, { id: 'type', label: 'Tipo', kind: 'text', required: true }] };
export interface ViewAction { readonly id: string; readonly label: string; readonly commandId: string; readonly selection: 'one' | 'many'; readonly requiresPreview?: boolean; }
export function validateViewAction(action: ViewAction, knownCommands: ReadonlySet<string>): void { if (action.id.trim() === '' || action.label.trim() === '' || !knownCommands.has(action.commandId)) throw new Error('Ação de view não está registrada no Command Registry.'); }
export function selectedEntities<T extends { readonly id: string }>(items: readonly T[], ids: readonly string[]): readonly T[] { const selected = new Set(ids); return items.filter((item) => selected.has(item.id)); }
