import { createHash } from 'node:crypto';
import type { AnalysisProvenance, DataDictionaryEntry, DatasetColumn, DatasetFormat, DatasetPreview, DatasetRecord, ReproducibilityManifest } from './model.js';

const formats: Readonly<Record<string, DatasetFormat>> = { csv: 'csv', tsv: 'tsv', json: 'json', xlsx: 'xlsx', parquet: 'parquet', zip: 'archive', tar: 'archive', gz: 'archive', png: 'image', jpg: 'image', jpeg: 'image', tif: 'image', tiff: 'image' };
export const datasetFormatForPath = (path: string): DatasetFormat => formats[path.toLowerCase().split('.').at(-1) ?? ''] ?? 'other';
export const fingerprintDataset = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');
export function registerDataset(input: Omit<DatasetRecord, 'format' | 'sha256'> & { readonly bytes: Uint8Array; readonly format?: DatasetFormat }): DatasetRecord { return { id: input.id, path: input.path, format: input.format ?? datasetFormatForPath(input.path), metadata: { ...input.metadata, title: input.metadata.title.trim() }, sha256: fingerprintDataset(input.bytes), ...(input.previousVersionId === undefined ? {} : { previousVersionId: input.previousVersionId }) }; }

const parseDelimited = (source: string, delimiter: string): DatasetPreview => { const rows = source.trimEnd().split(/\r?\n/u).map((line) => line.split(delimiter)); return { columns: rows[0] ?? [], rows: rows.slice(1) }; };
export function tabularPreview(source: string, format: DatasetFormat, limit = 50): DatasetPreview | undefined { if (format === 'csv' || format === 'tsv') { const parsed = parseDelimited(source, format === 'csv' ? ',' : '\t'); return { ...parsed, rows: parsed.rows.slice(0, limit), totalRows: parsed.rows.length }; } if (format === 'json') { const value: unknown = JSON.parse(source); if (!Array.isArray(value) || value.some((item) => typeof item !== 'object' || item === null || Array.isArray(item))) return undefined; const columns = [...new Set(value.flatMap((item) => Object.keys(item as Record<string, unknown>)))]; const rows = value.slice(0, limit).map((item) => columns.map((column) => String((item as Record<string, unknown>)[column] ?? ''))); return { columns, rows, totalRows: value.length }; } return undefined; }
const infer = (values: readonly string[]): DatasetColumn['type'] => { const present = values.filter((value) => value !== ''); if (present.length === 0) return 'unknown'; if (present.every((value) => /^(true|false)$/iu.test(value))) return 'boolean'; if (present.every((value) => Number.isFinite(Number(value)))) return 'number'; if (present.every((value) => /^\d{4}-\d{2}-\d{2}/u.test(value))) return 'date'; return 'string'; };
export function inferSchema(preview: DatasetPreview): readonly DatasetColumn[] { return preview.columns.map((name, index) => { const values = preview.rows.map((row) => row[index] ?? ''); return { name, type: infer(values), missing: values.filter((value) => value === '').length, distinct: new Set(values.filter(Boolean)).size }; }); }
export function validateDictionary(schema: readonly DatasetColumn[], dictionary: readonly DataDictionaryEntry[]): readonly string[] { return dictionary.flatMap((entry) => schema.some((column) => column.name === entry.column) ? [] : [`A coluna ${entry.column} não existe no dataset.`]); }
export function datasetCitation(dataset: DatasetRecord): Record<string, unknown> { return { id: `dataset-${dataset.id}`, type: 'dataset', title: dataset.metadata.title, ...(dataset.metadata.creator === undefined ? {} : { author: [{ literal: dataset.metadata.creator }] }), ...(dataset.metadata.collectedAt === undefined ? {} : { issued: { raw: dataset.metadata.collectedAt } }), ...(dataset.metadata.license === undefined ? {} : { license: dataset.metadata.license }), ...(dataset.metadata.source === undefined ? {} : { URL: dataset.metadata.source }), version: dataset.metadata.version, note: `SHA-256: ${dataset.sha256}` }; }
export function reproducibilityManifest(sourceRevision: string, datasets: readonly DatasetRecord[], analyses: readonly AnalysisProvenance[], artifacts: readonly string[]): ReproducibilityManifest { return { sourceRevision, datasets: datasets.map((dataset) => ({ id: dataset.id, sha256: dataset.sha256, ...(dataset.metadata.version === undefined ? {} : { version: dataset.metadata.version }) })), analyses: [...analyses], artifacts: [...artifacts] }; }
